### ISSUE TITLE
Doesn't work for the GPU runtime

### ISSUE THREAD

**Issue by manyuanbin** [drengskapur/docker-in-colab#1]
Would you please check to run on the GPU runtime?Btw, is "udocker" a nvidia-rutime or just dockerc?

**Comment by Ran-Mewo** [comment]
I was also trying to get GPU working in docker

Running `udocker --allow-root setup nvidia <container>`
Gives a `Error: host nvidia libraries not found`

**Comment by jonathanagustin** [comment]
<https://colab.research.google.com/gist/jonathanagustin/ec08cb9711bf9173b003f10ea7b30d51/docker-in-colab-test-1.ipynb>

@Ran-Mewo @manyuanbin works for me

**Comment by jonathanagustin** [comment]
Keep in mind that docker commands and udocker commands are not the same:

<https://github.com/indigo-dc/udocker?tab=readme-ov-file#examples>

It uses udocker underneath the hood.

**Comment by jonathanagustin** [comment]
<https://github.com/NVIDIA/nvidia-docker/issues/1735>

`udocker("run nvidia/cuda:12.4.1-cudnn-devel-rockylinux8")`

It works for me for all runtimes
